//
// JsonModel.h
//
// Json Mapping Automatically Generated By JsonToolkit Library for Objective C
// Diego Trinciarelli 2011
// To use this code you need to download and reference JSONKit
// https://github.com/johnezang/JSONKit
//

#import <Foundation/Foundation.h>
#import "JSONKit.h"

@class Organizer;
@class Ticket;
@class Venue;
@class Event;

@interface Organizer : NSObject

@property(nonatomic,retain) NSURL * url;
@property(nonatomic,retain) NSString * desc;
@property(nonatomic,retain) NSString * longDescription;
@property(nonatomic,retain) NSNumber * organizerId;
@property(nonatomic,retain) NSString * name;

@end


@interface Ticket : NSObject

@property(nonatomic,retain) NSString * desc;
@property(nonatomic,retain) NSDate * endDate;
@property(nonatomic,retain) NSNumber * min;
@property(nonatomic,retain) NSNumber * max;
@property(nonatomic,retain) NSString * price;
@property(nonatomic,retain) NSNumber * visible;
@property(nonatomic,retain) NSString * currency;
@property(nonatomic,retain) NSNumber * type;
@property(nonatomic,retain) NSNumber * ticketId;
@property(nonatomic,retain) NSString * name;

@end




@interface Venue : NSObject

@property(nonatomic,retain) NSString * city;
@property(nonatomic,retain) NSString * name;
@property(nonatomic,retain) NSString * country;
@property(nonatomic,retain) NSString * region;
@property(nonatomic,retain) NSNumber * longitude;
@property(nonatomic,retain) NSString * postalCode;
@property(nonatomic,retain) NSString * address2;
@property(nonatomic,retain) NSString * address;
@property(nonatomic,retain) NSNumber * latitude;
@property(nonatomic,retain) NSString * countryCode;
@property(nonatomic,retain) NSNumber * venueId;
@property(nonatomic,retain) NSString * latLong;

@end


@interface Event : NSObject

@property(nonatomic,retain) NSString * boxHeaderTextColor;
@property(nonatomic,retain) NSString * linkColor;
@property(nonatomic,retain) NSString * boxBackgroundColor;
@property(nonatomic,retain) NSString * timezone;
@property(nonatomic,retain) NSString * boxBorderColor;
@property(nonatomic,retain) NSString * logo;
@property(nonatomic,retain) Organizer * organizer;
@property(nonatomic,retain) NSString * backgroundColor;
@property(nonatomic,retain) NSNumber * eventId;
@property(nonatomic,retain) NSString * category;
@property(nonatomic,retain) NSString * boxHeaderBackgroundColor;
@property(nonatomic,retain) NSNumber * capacity;
@property(nonatomic,retain) NSNumber * numAttendeeRows;
@property(nonatomic,retain) NSString * title;
@property(nonatomic,retain) NSDate * startDate;
@property(nonatomic,retain) NSString * status;
@property(nonatomic,retain) NSString * desc;
@property(nonatomic,retain) NSDate * endDate;
@property(nonatomic,retain) NSString * tags;
@property(nonatomic,retain) NSString * timezoneOffset;
@property(nonatomic,retain) NSString * textColor;
@property(nonatomic,retain) NSString * titleTextColor;
@property(nonatomic,retain) NSSet * tickets;
@property(nonatomic,retain) NSString * created;
@property(nonatomic,retain) NSString * url;
@property(nonatomic,retain) NSString * boxTextColor;
@property(nonatomic,retain) NSString * privacy;
@property(nonatomic,retain) Venue * venue;
@property(nonatomic,retain) NSString * modified;
@property(nonatomic,retain) NSString * logoSsl;
@property(nonatomic,retain) NSString * repeats;

@end


//JsonModel.h End
