//
// JsonModel.m
//
// Json Mapping Automatically Generated By JsonToolkit Library for Objective C
// Diego Trinciarelli 2011
//

#import "Model.h"

@implementation Organizer


@end


@implementation Ticket



@end



@implementation Venue
@end


@implementation Event


@end

//JsonModel.m End
